feat: Add method for testing purposes
cloudscape-design/component-toolkit pull request #74
Opened 2024-07-11 06:26 UTC by fralongo

*Description of changes:*

Additional method to allow for testing of the analytics metadata. For example, it will allow to test that component names have a certain prefix, and that class names used for labels are part of a certain set.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-11 13:24 UTC, connorlanigan requested changes

2024-07-11 14:15 UTC, fralongo commented on src/internal/analytics-metadata/test-utils.ts
> +  while (currentNode && currentNode.tagName !== 'body') {
Good point, I removed it

2024-07-11 14:15 UTC, fralongo commented on src/internal/analytics-metadata/test-utils.ts
> +  return Object.keys(localMetadata).reduce((acc: any, key: string) => {
Done

2024-07-11 14:15 UTC, fralongo commented on src/internal/analytics-metadata/test-utils.ts
> +const getLabelSelectors = (localMetadata: any): Array<string> => {
I updated the name of the second method to be more clear

2024-07-12 11:59 UTC, connorlanigan approved these changes

2024-07-12 12:01 UTC, merged